#!/bin/sh

ASDF_TOOL_VERSIONS=$DOTFILES_LINKS_DIR/.tool-versions

asdf plugin add python
asdf install $(cat $ASDF_TOOL_VERSIONS_FILE | grep python)

asdf plugin add golang
asdf install $(cat $ASDF_TOOL_VERSIONS_FILE | grep golang)

asdf plugin add nodejs
bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
asdf install $(cat $ASDF_TOOL_VERSIONS_FILE | grep nodejs)
